### ISSUE TITLE
Missing chapters on home page

### ISSUE THREAD

**Issue by shushugah** [techworkersco/twc-site#127]
Here is a global list of chapters, please edit/add any missing chapters See #120 for inspiration. 
- [x] Austin #142
- [x] Bangalore
- [x] Berlin #116 
- [x] Boston
- [x] Chicago #195
- [x] DC (Washington)
- [x] LA #131 
- [x] London
- [ ] Montreal
- [x] NYC
- [ ] Ottawa
- [ ] Philadelphia
- [x] PDX (Portland) #120
- [x] San Diego #131
- [x] Seattle
- [x] SF Bay Area #128 
- [ ] South Bay / San Jose
- [x] South Florida #131 (Edit: Now Removed)

**Comment by scottwn** [comment]
Austin

**Comment by camilopayan** [comment]
South Florida

* [Meetup](https://www.meetup.com/South-Florida-Tech-Workers-Coalition/)
* [Facebook](https://www.facebook.com/southfltechworkers/)

**Comment by colombene** [comment]
Los Angeles - [Meetup](https://www.meetup.com/Tech-Workers-Coalition-LA/)

**Comment by shushugah** [comment]
> South Florida
> 
> * [Meetup](https://www.meetup.com/South-Florida-Tech-Workers-Coalition/)
> * [Facebook](https://www.facebook.com/southfltechworkers/)

Since this is multiple links, I can either directly link to the meetup page only, or create a South Florida page which includes both. And if so, what should the domain be? `/SouthFL` or `SouthFlorida` ?

**Comment by camilopayan** [comment]
I'd go for SouthFlorida

**Comment by shushugah** [comment]
LA, San Diego and South Florida folks, have a look! https://github.com/techworkersco/twc-site/pull/131

**Comment by shushugah** [comment]
> Austin

@scottwn any more info about Austin meetups or how to find them?

**Comment by rossPatton** [comment]
Some of these chapters i've never even heard of - should this issue be closed or updated?

**Comment by shushugah** [comment]
I’d prefer to keep this issue open, but will edit the original comment removing Philadelphia, Ottawa and Montreal since they never/are not active in past year.

**Comment by colombene** [comment]
You can remove LA - the meetup lapsed in June.
