### ISSUE TITLE
Update sign up thanks page

### ISSUE THREAD

**Issue by absolute-divergence** [techworkersco/twc-site#139]
https://github.com/techworkersco/twc-site/blob/develop/slack-thanks.md

This appears when you try to sign up for newsletter or slack, and links to old Bay Area Meetup page. Needs to be updated to not include a link at all, link back to home, or include a list of locals.

**Comment by shushugah** [comment]
List of locals would be nice!

**Comment by frextrite** [comment]
Hi @absolute-divergence and @shushugah 
By list of locals do you mean [this](https://techworkerscoalition.org/#connect) list which contains `Austin, Berlin, Boston, DC, LA, London, NYC, PDX, San Diego, Seattle, SF Bay Area, and South Florida.` And do we want to provide hyperlinks for every city?

**Comment by shushugah** [comment]
Yes exactly! `{% translate home.check_out_meeting.locations %}` will give you the list found here. https://github.com/techworkersco/twc-site/blob/develop/_i18n/en.yml#L28
