### ISSUE TITLE
Create 404.html file

### ISSUE THREAD

**Issue by shushugah** [techworkersco/twc-site#168]
Currently we get a very ugly 404 description with something like: 

# 404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: bla
RequestId: 8C20DDCBE295A4ED
HostId: 14uJGHIBAH3qUelJbkmLTaC6dM8QxpoihXXGfrXMYESEqCXSNGIosM1v/4NuTIF6QfUnexMSk9Q=
## An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html

**Comment by SoldierCorp** [comment]
I'll take it

**Comment by SoldierCorp** [comment]
Hi, please assign it to me

**Comment by shushugah** [comment]
Thank you for your contribution!
