### ISSUE TITLE
Inline CSS 

### ISSUE THREAD

**Issue by shushugah** [techworkersco/twc-site#170]
Similar to this commit, inline the CSS, so that it is not a blocking resource, or a separate HTTP call. Our CSS is extremely light weight as is.
 
https://github.com/shushugah/shushugah.github.io/commit/416b8d386993e8ed2f5f73fa575581c31ccf43e9

**Comment by prosarahgamal** [comment]
@shushugah can I work on this one?

**Comment by shushugah** [comment]
These are the three 3 blocking files, normalize.css, main.css and the jquery https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftechworkerscoalition.org

**Comment by prosarahgamal** [comment]
@shushugah can you please mention any resources for that capture tag you're using in that commit?

**Comment by shushugah** [comment]
Sure thing! I learnt about it first here, let me know if you have any more questions and thank you for picking this up! 

https://www.sitepoint.com/inline-css-in-jekyll/

**Comment by prosarahgamal** [comment]
very interesting!
