### ISSUE TITLE
Code of Conduct For Slack

### ISSUE THREAD

**Issue by melissamcewen** [techworkersco/twc-site#89]
I'd like to see a code of conduct for Slack that addresses some things that have come up in the past week including

- who the moderators are and how to get in contact with them
- prioritization of the safety of marginalized groups over comfort of privileged
- consequences for CoC violations

some good examples:
https://wealljs.org/code-of-conduct
https://lgbtq.technology/coc.html
https://docs.google.com/document/d/1OBYKDw4mDVX3A25Eo2g397XwF1NvteZgY_pVDnxoBu8/edit
https://docs.google.com/document/d/1UqK1_M6_I-sm9XLmSJt_SgYfo5tHg9z-ar5SHy62ENI/edit#heading=h.3u02axafjdg5

**Comment by shushugah** [comment]
This issue appears to me to be addressed. I'd close this issue, but it's an extremely important topic, so I'll leave it up, till others chime in. Below is the current weekly bot message in `#general` channel of slack

“:information_desk_person: Our Code of Conduct (https://techworkerscoalition.org/community-guide/) is in effect here. You can reach the Slack admins publicly in #meta-moderation or privately using the /admin command. CoC-related concerns online or off can also be directed to trustandsafety@techworkersco.org”

**Comment by absolute-divergence** [comment]
Yes, this is an extremely important topic. The bot message covers the first bullet point to some extent but not the latter two. Please do not close.

**Comment by shushugah** [comment]
I agree with point 2, but I think that should be reflected in the CoC itself, in terms of what is unacceptable behaviour. 

For the question about consequences, I like this section from the Berlin CoC. In addition to describing possible consequences, it clarifies that the CoC can use discretionary measures. 
```
Consequences of Unacceptable Behavior
Unacceptable behavior from any community member, including sponsors and those with decision-making authority, will not be tolerated. Anyone asked to stop unacceptable behavior is expected to comply immediately.

If a community member engages in unacceptable behavior, the community organizers may take any action they deem appropriate, up to and including a temporary ban or permanent expulsion from the community without warning (and without refund in the case of a paid event).
```
https://berlincodeofconduct.org/

**Comment by absolute-divergence** [comment]
I like that section, yeah. However this is way too large, important, and widely applicable a discussion to have in a Github issue. If you're interested in working on this further, more help is definitely needed - please reach out your contacts in TWC to ask how you can get connected with those who've been working on the CoC, Slack moderation, mediation, and other conduct-related issues in other locals.

**Comment by kidmillions** [comment]
gonna close this issue to move discussion of it away from github and website work.
